### ISSUE TITLE
jinja2 dependency pinned unexpectedly

### ISSUE THREAD

**Issue by consideRatio** [conda-forge/numpydoc-feedstock#22]
Hi, I'm arriving here after trying to understand why various dependencies was downgraded when installing various conda packages.

I found that jinja was downgraded to 3.0.3 from 3.1.2 because of numpydoc in conda-forge, but the requirements specified here is not in line with the projects setup.py declared dependencies. Due to that, I figure this can be a bug.

See https://github.com/conda-forge/numpydoc-feedstock/pull/17 for when jinja2 it was version constrained, and see the setup.py as defined by numpydoc in [here](https://github.com/numpy/numpydoc/blob/00854d5a438905fae46a6bed3db12cd505bb92e5/setup.py#L55) that doesn't declare an upper bound on jinja2 like this feedstock does.

**Comment by jschueller** [comment]
[9ba2e22](https://github.com/conda-forge/numpydoc-feedstock/commit/9ba2e22584fa3eeabe783ba2f5479a15cfae0b2a)

**Comment by consideRatio** [comment]
Thanks!
